export const defaultContent = {
  hero: {
    label: "Junior Developer · Mauritius",
    firstName: "Abdullah",
    lastName: "Mohamed",
    tagline: ["I don't aim for perfect.", "I aim for better."],
    subtext: "I build things to understand how they work.",
    subtextHighlight: "I'm methodical about getting sharper.",
    cta1: "Calibration Log",
    cta2: "Get in Touch",
    bgImage: "/images/hero-bg.jpeg",
  },
  about: {
    label: "The Archer",
    heading: "I know what I don't know.",
    headingHighlight: "I'm methodical about closing that gap.",
    body1: "I started building things because I wanted to understand how they worked. Not just use them. That impulse is still what drives me.",
    body2: "I approach problems the way I approach archery: understand the variables, control what you can, release with intention, and adjust based on where it lands. I'm not looking for a stage. I'm looking for a room where good thinking is valued.",
    values: ["Iterate", "Adjust", "Repeat"],
  },
  process: {
    label: "How I Think",
    heading: "Every problem is a shot.",
    subheading: "Deliberate, measured, and always followed by adjustment.",
    steps: [
      { step: "01", phase: "Target", description: "Understand the problem. Define what good looks like. Identify what I don't know before I touch a single line." },
      { step: "02", phase: "Aim", description: "Structure the approach. Research what I need. Plan before I build. A clear definition is worth more than three fast solutions." },
      { step: "03", phase: "Draw", description: "Build with focus. Every decision serves a purpose. No feature without a reason." },
      { step: "04", phase: "Release", description: "Ship, test, observe. The real feedback loop starts here. Not in the planning doc." },
      { step: "05", phase: "Adjust", description: "Read where it landed. Improve from what actually happened, not what was assumed. Every deviation is data." },
    ],
  },
  work: {
    label: "Calibration Log",
    heading: "Shots taken.",
    shots: [
      {
        number: "01",
        name: "E-Commerce Platform",
        type: "WordPress · WooCommerce",
        description: "Built a WooCommerce store from scratch. Product pages, cart, checkout, payment. The plugin handles a lot but you still have to know what you're doing.",
        adjustment: "Performance on WooCommerce takes real work. Test with real data early, not at the end.",
        tags: ["WordPress", "WooCommerce", "PHP"],
        accent: "from-[#00A7E1]/20 via-[#00A7E1]/10 to-charcoal-deep",
      },
      {
        number: "02",
        name: "Corporate Website",
        type: "Next.js · Payload CMS",
        description: "Built in Next.js with Payload as the CMS. Developers can actually work with Payload without things falling apart. Good fit for structured content.",
        adjustment: "Content modeling matters more than the design does. You find that out after the first content migration.",
        tags: ["Next.js", "Payload CMS", "TypeScript"],
        accent: "from-zinc-700/20 via-slate-800/30 to-charcoal-deep",
      },
      {
        number: "03",
        name: "Archery Training App",
        type: "Next.js",
        description: "Built a web app to track training sessions, log arrow groupings, and spot patterns over time. Scratched my own itch. Turned out harder than expected to design for a sport you're also practicing.",
        adjustment: "Being the user and the developer at the same time is useful. You can't lie to yourself about what's confusing.",
        tags: ["Next.js", "TypeScript", "PostgreSQL"],
        accent: "from-[#00A7E1]/15 via-[#00A7E1]/8 to-charcoal-deep",
      },
      {
        number: "04",
        name: "Multilingual Websites",
        type: "WordPress · WPML",
        description: "Sites in multiple languages for clients operating across different markets. More decisions at the content and structure level than I expected going in.",
        adjustment: "Translation is not just text. Structure, navigation, and content relationships all have to work in every language.",
        tags: ["WordPress", "WPML", "PHP"],
        accent: "from-[#00A7E1]/20 via-[#00A7E1]/10 to-charcoal-deep",
      },
    ],
  },
  archery: {
    label: "The Archer",
    heading: "Beyond the screen. Discipline in motion.",
    quote: "Precision is not a destination. It's a practice.",
    quoteBody: "You can repeat the same shot a thousand times and still find room to improve it. Not because you're failing. Because that's how mastery actually works. That's how I approach building. Not to be done. To be better.",
    imageLeft: "/images/archery-full.jpeg",
    imageRight: "/images/archery-aim.jpeg",
  },
  contact: {
    label: "MetaBox Technology",
    heading: "Want a website?",
    headingHighlight: "Get in touch.",
    body: "At MetaBox Technology we build websites that actually work: clean code, real performance, built to last. Whether it's a corporate site, an e-commerce store, or a custom web app, we'll get it done right.",
    ctaLabel: "LinkedIn · Abdullah Mohamed",
    captionName: "Abdullah Mohamed",
    captionRole: "Developer · MetaBox Technology",
    photo: "/images/mbx-photo.jpg",
  },
}

export type ContentData = typeof defaultContent
